(("package" . "zerotier-gtk4")
 ("version" . "1.0.0")
 ("release" . "1")
 ("section" . "utils")
 ("priority" . "optional")
 ("maintainer" . "Xu Xin <sxuxin@protonmail.com>")
 ("description" . "Creates virtual Ethernet networks of almost unlimited size. GTK4 UI.")
 ("prefix" . "/usr")
 ("languages" . "zh_CN")
 ("shebang" . "#! /usr/bin/chez --script"))
